 
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', "gcr.io/$PROJECT_ID/io2:v$BUILD_ID", '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "gcr.io/$PROJECT_ID/io2:v$BUILD_ID"]
  env:
  - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
  - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
    - 'set'
    - 'image'
    - 'deployment/io2'
    - 'io2=gcr.io/$PROJECT_ID/io2:v$BUILD_ID'
  env:
  - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
  - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
